{{- if and (.Values.auth.enabled) (not .Values.auth.existingAdminSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
  name: {{ template "adminSecret" . }}
type: Opaque
data:
  user: {{ .Values.auth.adminUser | b64enc }}
  password: {{ .Values.auth.adminPassword | b64enc }}
{{- end -}}
