{{- if and (.Values.auth.enabled) (not .Values.auth.existingKeySecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keySecret" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
type: Opaque
data:
  key.txt: {{ .Values.auth.key | b64enc }}
{{- end -}}
