# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: peer
      port: {{ .Values.port }}
  selector:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
