apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  {{ if .Values.defaultPassword }}
  rabbitmq-password: {{ .Values.defaultPassword | b64enc | quote }}
  {{ else }}
  rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.erlangCookie }}
  rabbitmq-erlang-cookie: {{ .Values.erlangCookie | b64enc | quote }}
  {{ else }}
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
