apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
   - name: http
     protocol: TCP
     port: {{ .Values.service.httpPort }}
     targetPort: {{ .Values.service.httpPort }}
   - name: amqp
     protocol: TCP
     port: {{ .Values.service.amqpPort }}
     targetPort: {{ .Values.service.amqpPort }}
  selector:
    app: {{ template "fullname" . }}
