{{- if .Values.head.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-head
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
    component: head
spec:
  ports:
  - port: {{ .Values.head.port }}
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
    component: head
{{- end }}
