{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.type }}
{{- if .Values.ingress.passwords }}
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: {{ .Release.Name }}-auth
    ingress.kubernetes.io/auth-realm: "Authentication Required"
{{- end }}
{{- if .Values.ingress.legoSupported }}
    kubernetes.io/tls-acme: "true"
{{- end }}
spec:
{{- if .Values.ingress.legoSupported }}
  tls:
  - secretName: {{ .Release.Name }}-tls
    hosts:
    - {{ .Values.ingress.host }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.elasticsearch.port }}
{{- if .Values.head.enabled }}
      - path: /head
        backend:
          serviceName: {{ .Release.Name }}-head
          servicePort: {{ .Values.head.port }}
{{- end }}
{{- end }}
