# Default values for kube-state-metrics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
exporter:
  image:
    repository: quay.io/coreos/kube-state-metrics
    tag: "v1.1.0"
    pullPolicy: IfNotPresent
  service:
    name: kube-state-metrics
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
  resources:
    limits:
     cpu: 200m
     memory: 400Mi
    requests:
     cpu: 100m
     memory: 200Mi
resizer:
  image:
    repository: gcr.io/google_containers/addon-resizer
    tag: "1.0"
    pullPolicy: IfNotPresent
  resources:
    limits:
     cpu: 100m
     memory: 30Mi
    requests:
     cpu: 100m
     memory: 30Mi
