apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cluster
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.bolt }}
      name: bolt
    - port: {{ .Values.ports.http }}
      name: http
  selector:
    app: {{ template "fullname" . }}
