apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: peer
      port: {{ .Values.ports.peer }}
  selector:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
