apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.exporter.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.exporter.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.exporter.service.internalPort }}
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.exporter.resources | indent 12 }}
        - name: addon-resizer
          image: "{{ .Values.resizer.image.repository }}:{{ .Values.resizer.image.tag }}"
          imagePullPolicy: {{ .Values.resizer.image.pullPolicy }}
          resources:
{{ toYaml .Values.resizer.resources | indent 12 }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --container=kube-state-metrics
            - --cpu={{ .Values.exporter.resources.requests.cpu }}
            - --extra-cpu=1m
            - --memory={{ .Values.exporter.resources.requests.memory }}
            - --extra-memory=2Mi
            - --threshold=5
            - --deployment=kube-state-metrics
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
