apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: "{{ .Values.exporter.service.externalPort }}"
spec:
  type: {{ .Values.exporter.service.type }}
  ports:
    - port: {{ .Values.exporter.service.externalPort }}
      targetPort: {{ .Values.exporter.service.internalPort }}
      protocol: TCP
      name: {{ .Values.exporter.service.name }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
